GET http://localhost:5075/books/6

###
POST http://localhost:5075/books
Content-Type: application/json

{
    "name": "Romeo and Juliet",
    "genre": "novel",
    "pages": "300",
    "price": 20.35,
    "releaseDate": "2021-06-23"
}

###

PUT http://localhost:5075/books/6
Content-Type: application/json

{
    "name": "Romeo and Juliet",
    "genre": "novel",
    "pages": "300",
    "price": 9.35,
    "releaseDate": "2025-06-23"
}

###

DELETE http://localhost:5075/books/2